### ISSUE TITLE
Doesn't work with dired-do-find-regexp-and-replace

### ISSUE THREAD

**Issue by seagle0128** [alexmurray/ivy-xref#2]
When I use `dired-do-find-regexp-and-replace` in `dired-mode` to multi-replace some strings in multiple files, `ivy-xref` doesn't work well. Actually it doesn't jump to the string properly, while it works after `(setq xref-show-xrefs-function #'xref--show-xref-buffer)`.

**Comment by alexmurray** [comment]
Thanks for reporting this issue - I hadn't used `dired-do-find-regexp-and-replace` before so hadn't come across it. Should be fixed in aa97103

**Comment by dgutov** [comment]
This could have been a good bug report for the Emacs core.

**Comment by dgutov** [comment]
Should be fixed in the upcoming Emacs 27.2 now: https://github.com/emacs-mirror/emacs/commit/749e4b7e0b04948f4805455e9505c6b855a84c96

BTW, I think I have said this before (I hope), but it doesn't make much sense for `ivy-xref` to change `xref-show-xrefs-function` in Emacs 27. Some other UI could do it, but since Ivy just lets you choose one option, that only matches the purpose of `xref-show-definitions-function`.

It was different in Emacs 26, though (there was no latter variable).

**Comment by alexmurray** [comment]
Oh nice - I would be happy to accept a PR to change this in `ivy-xref` for Emacs 27 if you think different behaviour is more correct.

**Comment by dgutov** [comment]
I can propose a patch for README. But here's what I have been wondering about.

Since `xref` is now also distributed separately (and requires Emacs 26.3), some Emacs 26 users could also install the latest version and benefit from this new distinction. To rely on that, though, `ivy-xref` would need to depend on that latest version (thus forcing its installation is not available).

Or we keep that version check and don't worry about the Emacs 26 users so much.
